services:
  - type: web
    name: health-tracker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn "wsgi:wsgi_app" --worker-class eventlet --workers 1 --bind 0.0.0.0:$PORT --timeout 120 --log-level debug
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_APP
        value: wsgi.py
      - key: FLASK_ENV
        value: production
      - key: PYTHONPATH
        value: .