"""add caloric goal field

Revision ID: 1f18859723aa
Revises: 1fe8f462bb4c
Create Date: 2025-02-06 01:57:35.338019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f18859723aa'
down_revision = '1fe8f462bb4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('caloric_goal', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entry', schema=None) as batch_op:
        batch_op.drop_column('caloric_goal')

    # ### end Alembic commands ###
