"""resync_database_state

Revision ID: 1fe8f462bb4c
Revises: df2e4798e7ab
Create Date: 2025-02-06 01:42:59.314979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fe8f462bb4c'
down_revision = 'df2e4798e7ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coros_access_token', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('coros_refresh_token', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('coros_token_expires_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('coros_athlete_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('coros_last_sync', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('coros_last_sync')
        batch_op.drop_column('coros_athlete_id')
        batch_op.drop_column('coros_token_expires_at')
        batch_op.drop_column('coros_refresh_token')
        batch_op.drop_column('coros_access_token')

    # ### end Alembic commands ###
