"""Add cross_training_minutes to Entry model

Revision ID: 20d611f8fdd3
Revises: 78bd4bff7b54
Create Date: 2025-02-06 03:07:04.008134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20d611f8fdd3'
down_revision = '78bd4bff7b54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cross_training_minutes', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entry', schema=None) as batch_op:
        batch_op.drop_column('cross_training_minutes')

    # ### end Alembic commands ###
