"""Add Garmin integration fields

Revision ID: 255e792f582a
Revises: 32cf7b525bba
Create Date: 2025-01-07 20:15:29.314166

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '255e792f582a'
down_revision = '32cf7b525bba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('garmin_email', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('garmin_password', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('garmin_last_sync', sa.DateTime(timezone=True), nullable=True))
        batch_op.alter_column('strava_access_token',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('strava_refresh_token',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('strava_token_expires_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('myfitnesspal_last_sync',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('myfitnesspal_last_sync',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('strava_token_expires_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('strava_refresh_token',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=150),
               existing_nullable=True)
        batch_op.alter_column('strava_access_token',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=150),
               existing_nullable=True)
        batch_op.drop_column('garmin_last_sync')
        batch_op.drop_column('garmin_password')
        batch_op.drop_column('garmin_email')

    # ### end Alembic commands ###
