"""Update User model with MyFitnessPal fields

Revision ID: 4117bcd49e82
Revises: c2a371bd108f
Create Date: 2024-12-28 18:45:06.069222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4117bcd49e82'
down_revision = 'c2a371bd108f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('myfitnesspal_username', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('myfitnesspal_password', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('myfitnesspal_last_sync', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('myfitnesspal_last_sync')
        batch_op.drop_column('myfitnesspal_password')
        batch_op.drop_column('myfitnesspal_username')

    # ### end Alembic commands ###
