"""remove_water_goal_from_entry

Revision ID: 4a7c177e6a4b
Revises: f189cc5bf7cf
Create Date: 2025-02-06 02:37:15.927841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a7c177e6a4b'
down_revision = 'f189cc5bf7cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entry', schema=None) as batch_op:
        batch_op.drop_column('water_goal')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('water_goal', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
