"""Update model fields

Revision ID: 4f8a8ff65492
Revises: d67ad69cf6f1
Create Date: 2024-12-16 15:52:21.228692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f8a8ff65492'
down_revision = 'd67ad69cf6f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('calories', sa.Integer(), nullable=True))
        batch_op.drop_column('calories_burned')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('calories_burned', sa.INTEGER(), nullable=True))
        batch_op.drop_column('calories')

    # ### end Alembic commands ###
