"""Add Strava Activity model

Revision ID: 5c49b4fb822d
Revises: 
Create Date: 2024-12-23 16:29:19.836213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c49b4fb822d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('strava_access_token', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('strava_refresh_token', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('strava_token_expires_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('strava_athlete_id', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('strava_athlete_id')
        batch_op.drop_column('strava_token_expires_at')
        batch_op.drop_column('strava_refresh_token')
        batch_op.drop_column('strava_access_token')

    # ### end Alembic commands ###
