"""Change steps to miles

Revision ID: 5cb193a95d99
Revises: 4f8a8ff65492
Create Date: 2024-12-16 15:54:06.791158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cb193a95d99'
down_revision = '4f8a8ff65492'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('miles', sa.Float(), nullable=True))
        batch_op.drop_column('steps')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('steps', sa.INTEGER(), nullable=True))
        batch_op.drop_column('miles')

    # ### end Alembic commands ###
