"""Add Garmin email and password fields

Revision ID: 6a7b169b349a
Revises: 255e792f582a
Create Date: 2025-01-07 20:24:00.352764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a7b169b349a'
down_revision = '255e792f582a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('garmin_access_token', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('garmin_refresh_token', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('garmin_token_expires_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('garmin_token_expires_at')
        batch_op.drop_column('garmin_refresh_token')
        batch_op.drop_column('garmin_access_token')

    # ### end Alembic commands ###
