"""Add water_goal field to Entry model

Revision ID: 78bd4bff7b54
Revises: 4a7c177e6a4b
Create Date: 2025-02-06 02:45:02.218852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78bd4bff7b54'
down_revision = '4a7c177e6a4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('water_goal', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entry', schema=None) as batch_op:
        batch_op.drop_column('water_goal')

    # ### end Alembic commands ###
