"""Add steps and other columns

Revision ID: d67ad69cf6f1
Revises: 
Create Date: 2024-12-16 15:45:07.850259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd67ad69cf6f1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('calories_burned', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('water_intake', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('steps', sa.Integer(), nullable=True))
        batch_op.alter_column('sleep_hours',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('running_mileage',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.drop_column('hydration')
        batch_op.drop_column('calories')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('calories', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('hydration', sa.FLOAT(), nullable=False))
        batch_op.alter_column('running_mileage',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('sleep_hours',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.drop_column('steps')
        batch_op.drop_column('water_intake')
        batch_op.drop_column('calories_burned')

    # ### end Alembic commands ###
