"""Add Garmin athlete ID field

Revision ID: d921a914ff0d
Revises: 6a7b169b349a
Create Date: 2025-01-07 20:32:53.080671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd921a914ff0d'
down_revision = '6a7b169b349a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('garmin_athlete_id', sa.String(length=50), nullable=True))
        batch_op.drop_column('garmin_email')
        batch_op.drop_column('garmin_password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('garmin_password', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('garmin_email', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
        batch_op.drop_column('garmin_athlete_id')

    # ### end Alembic commands ###
