"""add_water_goal_to_entry

Revision ID: f189cc5bf7cf
Revises: 1f18859723aa
Create Date: 2025-02-06 02:32:57.086195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f189cc5bf7cf'
down_revision = '1f18859723aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('water_goal', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entry', schema=None) as batch_op:
        batch_op.drop_column('water_goal')

    # ### end Alembic commands ###
